language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"

matrix:
  allow_failures:
  - python: "3.4"

notifications:
  email: false

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

install:
  - pip install .[sampling,plotting,testing]
  - pip install coveralls

script: nosetests --with-coverage --cover-package=flavio

after_success: coveralls
