language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
services:
  - xvfb


notifications:
  email: false

install:
  - pip install numpy --upgrade  # for pypmc
  - pip install .[sampling,plotting,testing]
  - pip install coveralls

script: nosetests --with-coverage --cover-package=flavio

after_success: coveralls
